quarkus.application.name=bloom-notification-service
quarkus.http.port=8084
quarkus.http.cors=true
quarkus.swagger-ui.always-include=true
quarkus.mailer.from=no-reply@bloom.com
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.mock=false
