quarkus.application.name=bloom-gateway
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.swagger-ui.always-include=true

bloom.services.catalog.url=http://localhost:8081
bloom.services.order.url=http://localhost:8082
bloom.services.inventory.url=http://localhost:8083