quarkus.application.name=bloom-inventory-service
quarkus.http.port=8083
quarkus.http.cors=true
quarkus.swagger-ui.always-include=true

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/bloom_db
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.flyway.table=flyway_inventory_history
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=0.0.0

kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.incoming.orders-in.topic=bloom.orders.created
mp.messaging.incoming.orders-in.group.id=inventory-service-group
mp.messaging.incoming.orders-in.auto.offset.reset=earliest
mp.messaging.incoming.orders-in.value.deserializer=com.bloom.inventory.messaging.OrderCreatedEventDeserializer

mp.messaging.outgoing.inventory-out.connector=smallrye-kafka
mp.messaging.outgoing.inventory-out.topic=bloom.inventory.events
mp.messaging.outgoing.inventory-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer