global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'bloom-gateway'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'bloom-catalog-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['catalog-service:8081']

  - job_name: 'bloom-order-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['order-service:8082']

  - job_name: 'bloom-inventory-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['inventory-service:8083']
